# -*- coding: utf-8 -*-
"""Functional_data_access_and_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p753nZUdAOHgS3BbaWcGGRYzFJbal-Tf
"""

!pip install uv
!uv pip install datajoint
!uv pip install caveclient

from google.colab import drive
drive.mount('/content/drive')


import os
import pickle
import datajoint as dj
from caveclient import CAVEclient
import pandas as pd
import numpy as np
# from microns_phase3 import nda, utils
dj.config


# CAVE initiation
client = CAVEclient()
# client.auth.get_new_token()
# client.auth.save_token(token = what_you_get_from_get_new_token)
client = CAVEclient('minnie65_public')
client.materialize.version = 1718
timestamp = client.materialize.get_timestamp(version=client.materialize.version)
client.materialize.get_tables()

# 读取Google drive中缓存的神经元文件
CACHE_DIR = '/content/drive/MyDrive/WenLab/scale_invariant/cache/cache_data_from_MICrONs'
os.makedirs(CACHE_DIR, exist_ok=True)
PROOF_CACHE = os.path.join(CACHE_DIR, 'df_proofread_clean.pkl')
# COREG_CACHE = os.path.join(CACHE_DIR, 'df_coreg_filtered.pkl')
INHIB_CACHE = os.path.join(CACHE_DIR, 'df_inh_neuron_filtered.pkl')
EXCIT_CACHE = os.path.join(CACHE_DIR, 'df_ext_neuron_filtered.pkl')
SYN_IN_COMBINED_CACHE = os.path.join(CACHE_DIR, 'synapses_in_combined.pkl')
SYN_OUT_COMBINED_CACHE = os.path.join(CACHE_DIR, 'synapses_out_combined.pkl')
# GLOBAL_IDS_CACHE = os.path.join(CACHE_DIR, 'global_root_ids.pkl')
# GLOBAL_IDS_CACHE_INHIB = os.path.join(CACHE_DIR, 'global_inh_root_ids.pkl')

if os.path.exists(EXCIT_CACHE):
  with open(EXCIT_CACHE, 'rb') as f:
    df_ext_filtered = pickle.load(f)
df_ext_root_id = df_ext_filtered[['target_id_ext', 'pt_root_id']].drop_duplicates()
df_ext_root_id.head()

df_coreg = client.materialize.query_table('coregistration_auto_phase3_fwd_apl_vess_combined_v2')
df_coreg = df_coreg[df_coreg['valid'] == True]
# df_coreg.columns
# 修改合并逻辑：利用 df_ext_root_id 筛选 df_coreg
# 注意：根据 df_ext_root_id 的内容，这里使用 target_id_ext 进行匹配
df_coreg_ext = pd.merge(df_coreg, df_ext_root_id, left_on='pt_root_id', right_on='pt_root_id', how='inner')

# 统计唯一的 pt_root_id 数量
unique_root_ids_count = df_coreg_ext['pt_root_id'].nunique()
n = df_ext_root_id['target_id_ext'].nunique()
print(f"表中唯一的 pt_root_id 数量: {unique_root_ids_count}, df_ext_root_id 表中的这一数量为: {n}")

# 获取唯一的 pt_root_id 列表
unique_root_ids = df_coreg_ext['pt_root_id'].unique()

# """几个待解决的问题：一个scan里的功能数据是在一个时间点里的吗？有分析意义吗？"""

# Sort the dataframe by session, scan_idx, and unit_id
df_coreg_ext_sorted = df_coreg_ext.sort_values(by=['session', 'scan_idx', 'unit_id'])

# Count the number of unique neurons (pt_root_id) per scan (session + scan_idx)
scan_stats = df_coreg_ext_sorted.groupby(['session', 'scan_idx']).agg(
    neuron_count=('pt_root_id', 'nunique'),
    unit_list=('unit_id', list)
).reset_index()

print("Each scan's neuron counts:")
display(scan_stats)

print("\nSorted coregistration data (first 5 rows):")
display(df_coreg_ext_sorted.head())

# 提取 session=7 且 scan_idx=4 的内容
df_max_num_scan = df_coreg_ext_sorted[(df_coreg_ext_sorted['session'] == 7) & (df_coreg_ext_sorted['scan_idx'] == 4)]

print("\nSession 7, Scan 4 的数据 (前5行):")
display(df_max_num_scan.head())

# !pip install microns_phase3
# from microns_phase3 import nda, utils
